services:
  stardrive:
    image: qqays/stardrive:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/stardrive/data
    environment:
      - STARDRIVE_APP_SECRET="your-secret-here"
    restart: always